# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build App
        run: |
          xcodebuild build \
            -scheme "Reverse Scrolling" \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package App into ZIP
        run: |
          cd build/Build/Products/Release
          zip -r ReverseScrolling.zip *.app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReverseScrolling-macOS
          path: build/Build/Products/Release/*.zip
          
